---
language: python
python: "2.7"

env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl python-pip python-apt gcc

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - printf '[defaults]\nroles_path = ../' > ansible.cfg

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/$SITE --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Make sure Java is installed.
  - >
    which java
    && (echo 'Java is installed: pass' && exit 0)
    || (echo 'Java is installed: fail' && exit 1)

  # Make sure Elasticsearch is up
  - >
    curl -s http://localhost:9200
    | grep -q 'You Know, for Search'
    && (echo 'Elasticsearch is responding: pass' && exit 0)
    || (echo 'Elasticsearch is responding: fail' && exit 1)

  # Make sure Kibana is accessible
  - >
    curl -s http://localhost:5601/app/kibana
    | grep -q 'the kibana you know and love'
    && (echo 'Kibana is accessible: pass' && exit 0)
    || (echo 'Kibana is accessible: fail' && exit 1)

  # Make sure nginx is proxifying Kibana requests
  - >
    curl -s http://localhost:80/app/kibana
    | grep -q 'the kibana you know and love'
    && (echo 'Proxy to Kibana: pass' && exit 0)
    || (echo 'Proxy to Kibana: fail' && exit 1)
