---
- name: Kibana archive available
  get_url:
    dest=/opt
    url=https://download.elasticsearch.org/kibana/kibana/kibana-{{ elk_kibana.version }}.tar.gz
    owner={{ elk_nginx.user }} group={{ elk_nginx.user }}
  sudo: yes

- name: Kibana archive uncompressed
  unarchive:
    src=/opt/kibana-{{ elk_kibana.version }}.tar.gz
    dest=/opt copy=no
    owner={{ elk_nginx.user }} group={{ elk_nginx.user }}
  sudo: yes

- name: Uncompressed Kibana linked to path
  file:
    src=/opt/kibana-{{ elk_kibana.version }}
    path={{ elk_kibana.path }} state=link
    owner={{ elk_nginx.user }} group={{ elk_nginx.user }}
  sudo: yes

- name: Kibana files ownership
  file:
    path={{ elk_kibana.path }}
    state=directory
    owner={{ elk_nginx.user }} group={{ elk_nginx.user }} recurse=yes
  changed_when: False
  sudo: yes

- name: Generate kibana htpassword
  shell:
    chdir=/etc/nginx/conf.d
    creates=/etc/nginx/conf.d/.kibana.htpasswd
    echo "{{ elk_kibana.user }}:$(openssl passwd -crypt {{ elk_kibana.password }}):kibana" |tee .kibana.htpasswd
  sudo: yes
  register: http_pass_gen

- name: Kibana htpassword file permissions
  file:
    path=/etc/nginx/conf.d/.kibana.htpasswd
    owner={{ elk_nginx.user }} group=root mode=400
  sudo: yes
  when: http_pass_gen|changed

- name: Nginx config file
  template:
    src=kibana-default.j2
    dest=/etc/nginx/conf.d/kibana.conf
    owner=root group=root mode=644
  sudo: yes
  notify: Restart nginx
